### ISSUE TITLE
When recording is saved the app crashes 

### ISSUE THREAD

**Issue by SimplyAsm** [F0x1d/LogFox#101]
[crash-com-f0x1d-logfox-02_02-16-08-25_407.zip](https://github.com/F0x1d/LogFox/files/14138883/crash-com-f0x1d-logfox-02_02-16-08-25_407.zip)

The log is taken from Logfox !

**Comment by F0x1d** [comment]
Check out apk from [here](https://github.com/F0x1d/LogFox/actions/runs/7756395312)
