### ISSUE TITLE
Export current logs 

### ISSUE THREAD

**Issue by Turhvjbufv** [F0x1d/LogFox#102]
Add an option to export all logs that are in logfox tab(with filters) instead of having to record them again
Maybe press on three dots and export option there

**Comment by F0x1d** [comment]
done in 1b0edbfa7585497ea9627de44a65afef40f35468

**Comment by indrastorms** [comment]
It's exporting raw logs. How to export filtered logs?

**Comment by F0x1d** [comment]
What do you mean? You select what to export, why would you need additional filtering? 

Or are you talking about parts of log which should be included?

**Comment by indrastorms** [comment]
> What do you mean? You select what to export, why would you need additional filtering?
> 
> Or are you talking about parts of log (like time, date) which should be included?

Oh didn't know i can select logs 😅
