### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [F0x1d/LogFox#104]
Is the 1.5.6 apk built from the tag? Could you please take a look? Thanks!

**Comment by F0x1d** [comment]
As i see, 1.5.6 is not available on fdroid yet

**Comment by linsui** [comment]
The diff: 
[diff.html.zip](https://github.com/F0x1d/LogFox/files/14228856/diff.html.zip)

**Comment by F0x1d** [comment]
Where can i get the `.apk`?
<img width="669" alt="image" src="https://github.com/F0x1d/LogFox/assets/39910552/8b8ee077-1775-456e-884e-00dea224c785">
I can't see there even 1.5.5

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/6143435198/artifacts/file/tmp/com.f0x1d.logfox_58.apk It's not published since the build failed.

**Comment by F0x1d** [comment]
Got it, but i don't really know the reason yet

**Comment by linsui** [comment]
Could you do a clean build from https://github.com/F0x1d/LogFox/commit/5dddf32689077e8084d5fc14006295d076365ef0?

**Comment by linsui** [comment]
It's reproducible, thanks! Please update the apk in release.

**Comment by F0x1d** [comment]
Done, can it be closed now?

**Comment by linsui** [comment]
Yes, thanks!

**Comment by linsui** [comment]
2.0.0 apk is built from c9e41a8cb055f1fba0789a5d7d183a224a9ca3cd, could you please rebuild it from the tag?

**Comment by F0x1d** [comment]
Will soon build 2.0.1

**Comment by F0x1d** [comment]
Built 2.0.1 from ci, should be ok

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
can we reopen?

https://gitlab.com/fdroid/fdroiddata/-/jobs/7618039004#L3535

**Comment by F0x1d** [comment]
According to logs that's not about being non reproducible. Or am I wrong?

**Comment by licaon-kter** [comment]
Your built

Ours didn't

So it's not reproducible :)

**Comment by F0x1d** [comment]
got it, thanks!

**Comment by linsui** [comment]
@F0x1d The apk name changed in 2.0.3. Is this intended?

**Comment by F0x1d** [comment]
Yes, it has become a default one since v2.0.0. But now I am too tired to change it manually

**Comment by drogga** [comment]
It probably took longer to type the response, then it would've take to rename the `app-release.apk` asset of `v2.0.3` in `/releases` ...
