### ISSUE TITLE
Publish on Accrescent store

### ISSUE THREAD

**Issue by shuvashish76** [F0x1d/LogFox#117]
Would you consider publishing it on [Accrescent](https://github.com/accrescent/accrescent); an alternative android app store?

See their guide: https://accrescent.app/docs/guide/getting-started/

**Comment by F0x1d** [comment]
<img width="936" alt="image" src="https://github.com/user-attachments/assets/1901cc83-7db6-4d36-91f0-6a4676ab947e">

**Comment by shuvashish76** [comment]
The app store is installed by default in GrapheneOS. The project is still "Beta", hence new developer registrations are disabled. Currently developers need to be whitelisted before they can publish to the store.
Their matrix room : https://matrix.to/#/#accrescent:matrix.org

**Comment by F0x1d** [comment]
I currently do not want to use matrix. Ping me when they will give access to everyone
