### ISSUE TITLE
[Request] Block specific crash notifications

### ISSUE THREAD

**Issue by aaa1115910** [F0x1d/LogFox#121]
### Problem

This happens on my phone
- System updates cause problems with certain system processes, causing crash notifications to pop up every tens of seconds.
- Some software will trigger a crash notification when opened (for example, opening Baidu Tieba will trigger a zygote crash)

These crashes bring hundreds of notifications every day, and there is no way to block them, but I don’t want to close LogFox either.

### Expected Solution

Add a block list to block some of the crash record notifications

**Comment by F0x1d** [comment]
I will definitely find free time to add it

**Comment by Jesse205** [comment]
![Screenshot_20240605_212417_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/b3872726-7ef6-439f-8e9b-62cee32b0158)

Yes, besides crashes, there will also be a large number of ANRs

**Comment by F0x1d** [comment]
Done in v2.0.0
