### ISSUE TITLE
[Question] Get exported logs like those displayed within the app

### ISSUE THREAD

**Issue by Go-rom** [F0x1d/LogFox#123]
Hi

i'm having some difficulties to get copied/exported log with the same structure like the one displayed in the app.
Maybe i'm missing something,  i hope you could tell me.

Here's an example with a log sample :

![Testlog_screenshot](https://github.com/F0x1d/LogFox/assets/1423386/a714148f-0e2b-4637-bc47-4df9764a14ca)

And when i choose copy/extended copy/export, i'm getting this structure : 

> 1713545881.722 10828 16587 16587 I ViewRootImpl@1f16307[MainActivity]: ViewPostIme pointer 0
1713545881.778 10828 16587 16587 I ViewRootImpl@1f16307[MainActivity]: ViewPostIme pointer 1
1713545881.786 10828 16587 16621 D OpenGLRenderer: setSurface called with nullptr
1713545881.786 10828 16587 16621 D OpenGLRenderer: setSurface() destroyed EGLSurface
1713545881.786 10828 16587 16621 D OpenGLRenderer: destroyEglSurface
1713545881.787 10828 16587 16587 I ViewRootImpl@1f16307[MainActivity]: dispatchDetachedFromWindow
1713545881.802 10828 16587 16587 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
1713545881.802 10828 16587 16587 D InputTransport: Input channel destroyed: 'e60ddbc', fd=126
1713545881.816 10828 16587 16587 W TabLayout: MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
1713545881.819 10828 16587 16587 I ¯\_(ツ)_/¯ : Loading saved AuthData
1713545881.845 10828 16587 16675 I ¯\_(ツ)_/¯ : Loading saved AuthData
1713545881.846 10828 16587 16675 I ¯\_(ツ)_/¯ : Proxy is disabled
1713545881.850 10828 16587 16587 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.aurora.store.nightly/com.aurora.store.MainActivity
1713545881.850 10828 16587 16587 D InsetsSourceConsumer: ensureControlAlpha: for ITYPE_STATUS_BAR on com.aurora.store.nightly/com.aurora.store.MainActivity
1713545881.852 10828 16587 16587 I ViewRootImpl@2ee88b1[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1

Let's focus on the first line,  i would like to get this output like the screenshot : 
> 18:58:01.722 I ViewRootImpl@1f16307[MainActivity]: ViewPostIme pointer 0

About device/versions : 
Samsung S10 Android 12 (not rooted)
LogFox 1.5.7 (F-Droid)

And thank you for this great app btw !

**Comment by F0x1d** [comment]
Logs are exported in the same format as they are read from the `logcat`, so that you can read them in another LogFox app

**Comment by Go-rom** [comment]
Ok thank you for your quick answer and for turning this question into a feature request.
Now i understand the purpose of that format. 👍🏻

**Comment by F0x1d** [comment]
Done in v2.0.0
