### ISSUE TITLE
[FR] non-root logcat via remote debugging

### ISSUE THREAD

**Issue by BlueAmulet** [F0x1d/LogFox#131]
**Description:**
If you have another device such as a computer or a secondary phone, you can enable adb over tcpip, which would allow LogFox to connect to itself and read logs without root. Some other logcat reader applications support this method of reading logs without root, but do not come with the features that LogFox has.

**Idea:**
1. Connect phone to computer
2. Run `adb tcpip 5555`
3. LogFox can now read logs by connecting to the phone over port 5555

**Comment by F0x1d** [comment]
Shizuku supports this feature, if I get it right, why not using it?

**Comment by BlueAmulet** [comment]
I did not realize Shizuku was a rootless modification system, apologies.
