### ISSUE TITLE
Create notification on crash

### ISSUE THREAD

**Issue by Turhvjbufv** [F0x1d/LogFox#134]
Every time an app crashes it automatically creates a separate notification for that app, which is something you don't always want, also, can you add an option to "reset" all notificationa to the base crashes one(the one that's for all apps)

**Comment by F0x1d** [comment]
You mean having one notification which will be overridden with another notification on another crash?

**Comment by F0x1d** [comment]
Oh, you are about notification channels. Yeah, they are separate, but I still don't understand the problem. If you want to disable all you can do it in LogFox settings

**Comment by F0x1d** [comment]
Added switch in 2.0.1
