### ISSUE TITLE
Add Scrollbar view

### ISSUE THREAD

**Issue by shuvashish76** [F0x1d/LogFox#139]
Adding a scroll button would allow users to jump screen quickly.

Have a look on this libraries
- https://github.com/reddit/IndicatorFastScroll
- https://github.com/nanihadesuka/LazyColumnScrollbar

**Comment by F0x1d** [comment]
And on which screen do you want this?

**Comment by shuvashish76** [comment]
LogViewer page. For example see how it's implemented in [AppManager](https://github.com/MuntashirAkon/AppManager)'s LogViewer which uses [this](https://github.com/zhanghai/AndroidFastScroll) library.

**Comment by F0x1d** [comment]
I don't like the appearance TBH

![image](https://github.com/user-attachments/assets/b7d4a795-b766-42be-b036-dcb767e8161f)

**Comment by drogga** [comment]
The image is broken.

**Comment by drogga** [comment]
The image might not show up here, but I've DLed it and I don't know what you mean, it looks OK to me, a scrollbar as any, what is there to not like in the appearance of it?
