### ISSUE TITLE
[BUG] Honor logger not working

### ISSUE THREAD

**Issue by Vladik01-11** [F0x1d/LogFox#141]
Hello, ran into a problem that logger services, system and shizuku, do not output anything, restarting the service, exit and exit via notification do not work.
No filters, Honor device, android 13, buffer size is not 0.

P.S. while I was writing I decided to reboot the device, caught the crash of the phone services, but all the above was unchanged.

**Comment by F0x1d** [comment]
You mean LogFox caught the crash in background, but is unable to display logs in list?

**Comment by F0x1d** [comment]
It turned out this issue is about Huawei system restrictions. I can do nothing with it
