### ISSUE TITLE
Crash not found

### ISSUE THREAD

**Issue by opk12** [F0x1d/LogFox#142]
I am [crashing Cirrus](https://github.com/woheller69/omweather/issues/91) (previously known as omWeather) like this, but LogFox could not find the crash.

- Open Cirrus.
- Tap the map icon at the top right.
- Press Play at the top.
- Press the Back button.
- Observe crash.
- Open LogFox, expect a notification for the crash.
- LogFox does not make the notification.

**Comment by opk12** [comment]
#143

**Comment by F0x1d** [comment]
Are you talking about 
1. "Loading" while crashes are being searched using search bar
2. "Loading" when you open crashes tab and until you see apps in list
3. "Loading" before crash is handled and appeared in list?

I guess it is about 1 and 2.
