### ISSUE TITLE
Recent crash

### ISSUE THREAD

**Issue by PeterKW** [F0x1d/LogFox#147]
Is it possible to sort by recent crash and ungroup by app?

**Comment by F0x1d** [comment]
You can sort crashes by newness on crashes screen

**Comment by PeterKW** [comment]
I haven't figured out how to do this

**Comment by PeterKW** [comment]
I haven't figured out how to do this

![Screenshot_20241127-205824.png](https://github.com/user-attachments/assets/b7014407-2aef-4f5f-9bba-a453e617ab0c)

**Comment by PeterKW** [comment]
Seems to be in a strange order, I'll try again
