### ISSUE TITLE
Shizuku support

### ISSUE THREAD

**Issue by kiber-io** [F0x1d/LogFox#15]
Is it possible to add Shizuku support? I'm not sure if it provides the ability to read the logcat, but what if?

**Comment by F0x1d** [comment]
I'll check if it is possible

**Comment by F0x1d** [comment]
[Logra](https://github.com/wingio/Logra) uses Shizuku, so it is possible I'll also add support soon

**Comment by kiber-io** [comment]
Logra uses Shizuku only to automatically grant permission to read logs. But since android 13, this permission is not remembered and is constantly being re-requested. Maybe it is possible to automatically grant permission every time, or to read logs directly through shizuku?

**Comment by F0x1d** [comment]
It is done through terminal, i think it is possible to access logcat

**Comment by F0x1d** [comment]
Done in 1.3.2
