### ISSUE TITLE
[bug]Unable to get logs

### ISSUE THREAD

**Issue by atuy1219** [F0x1d/LogFox#152]
Android 15, non-root , pixel 6a

As the title says. Can't get logs
Also, there is a problem that the exit button cannot be finished even if you press the exit button from the notification.

https://github.com/user-attachments/assets/ae49b913-eaff-4f15-a5ea-f46c3a539afa

**Comment by drogga** [comment]
It might sound pointless, but try to force stop it from the App Info and launch it again _(it usually makes the Exit from the notification work right away every time for me after this)_.

**Comment by F0x1d** [comment]
Wasn't the issue with Exit button fixed in latest version?

**Comment by drogga** [comment]
It seems not, or at least in my 'edge' case on/in android-x86-8.1-r6.iso (Root Method), I've tested v2.0.4 couple of hours since its release, but at this point I gave up and consider my issues specific to me and got used to them and don't even bother to report them, this was just a suggestion to @atuy1219, which it won't hurt to try, it costs the OP nothing ;)

**Comment by F0x1d** [comment]
@atuy1219 could you check the issue on this build? (just replace `.zip` with `.apk`) 

If issue is still here, then, please, go to LogFox settings and tap "share logs" button. Then send this file to me (telegram - @F0x1d)

[app-debug.zip](https://github.com/user-attachments/files/17686791/app-debug.zip)

**Comment by atuy1219** [comment]
> It might sound pointless, but try to force stop it from the App Info and launch it again _(it usually makes the Exit from the notification work right away every time for me after this)_.

Unfortunately, it didn't work on my device.


>@atuy1219 could you check the issue on this build? (just replace .zip with .apk)
>
>If issue is still here, then, please, go to LogFox settings and tap "share logs" button. Then send this file to me (telegram - @F0x1d)

I’m on it.

**Comment by F0x1d** [comment]
It turned out logs buffer was set to off
