### ISSUE TITLE
Notification Channel Grouping

### ISSUE THREAD

**Issue by abdalmoniem** [F0x1d/LogFox#153]
Right now if I disable `use separate notifications channels for crashes notifications` it creates only one channel for the notifications, but doesn't group the notifications by app like in the main UI of the app. That would be more convenient for a unified experience across the whole app

**Comment by F0x1d** [comment]
This setting was made as a request from someone, who wanted to setup notification channel right for all crashes

**Comment by abdalmoniem** [comment]
actually, it is working now, it is grouping all the crashes which is better than what I was suggesting, so I'll close this issue now 😊
![Screenshot_2024-11-10-21-01-02-17_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/b023dec4-be63-40ee-bfce-c4e252914138)
