### ISSUE TITLE
Is this type of battery usage normal? 

### ISSUE THREAD

**Issue by MillionsToOne** [F0x1d/LogFox#158]
Is this normal? Feel free to close if it's intended. ![Screenshot_20241121-152003_Settings.png](https://github.com/user-attachments/assets/0a1bfe7f-bda9-4ae6-87b0-e63798329f4d)

**Comment by Lobo6780** [comment]
For me it's the same on 2.0.5 version I just downgraded to 2.0.4 and it's normal again.

**Comment by F0x1d** [comment]
I will take a look

**Comment by F0x1d** [comment]
Can you check battery consumption on this build? https://github.com/F0x1d/LogFox/actions/runs/11997115146/artifacts/2229782198

**Comment by MillionsToOne** [comment]
I'll report back after some time.

**Comment by MillionsToOne** [comment]
![Screenshot_20241124-212837_Settings.png](https://github.com/user-attachments/assets/a029ef9a-fcfc-41f2-bab0-e19c3f257d7c)

Seems better

**Comment by kaduvert** [comment]
turns out i'm still on v2.0.5 because 2.0.6 is not on F-Droid yet...

**Comment by MillionsToOne** [comment]
> turns out i'm still on 2.0.5 because 2.0.6 is not on F-Droid yet...
> 
> this author has to get his priorities right, this has been released a week ago and sensible people who don't obsessively update their logging app through github are having their phones drained FOR 2+ WEEKS and still ongoing!
> 
> its one thing releasing bs unstable builds with changes only the nerdiest of nerds would even notice, but IF YOU DO DO, FIX THEM ASAP!
> why tf is this "closed as completed"?!

It's on Izzydroid. Take or leave it
