### ISSUE TITLE
[meta] F-Droid still recommends battery-draining v2.0.5

### ISSUE THREAD

**Issue by kaduvert** [F0x1d/LogFox#161]
yeah what's going on?
my phone has been getting drained for 2+ weeks and if i hadn't randomly checked battery usage it still would be.

1) what was the cause of this?
2) why has this reached end-users?
3) why can battery-draining micro-releases with hardly noticeable positive changes be released instantly while fixes for life-altering bs code have taken and are still taking over 2 weeks to reach end users?

it's one thing if this gets fully pushed to the end-user, but i think there is a bigger problem with this developer here.

no hate on you man, you've built an amazing logcat reader, but things like this can't be happening.

**Comment by kaduvert** [comment]
> you can always download it from the [releases tab](https://github.com/F0x1d/LogFox/releases/) and it's f-droid's problem that they are not updating the app, redundant issue.

1) no normal person with things to do manually updates their logcat reader.
2) as i said, i think there is a bigger problem with the developers mentality. not everything is a coding problem, carelessly pushing redundant micro-releases, occasionally resulting in problems like this with real-world impact is not F-Droid's fault

**Comment by kaduvert** [comment]
i'd perhaps even argue @rywz , that if the developer hadn't endlessly tormented F-Droid with his micro-releases, the new release could have already been made available

**Comment by F0x1d** [comment]
Come on, this is not a big tech company, that's just me, I don't have QAs to test my app

The problem was in my reading logs loop, you can check the commit with fix to see more

I don't have enough free time to keep this app enabled for a lot of time in background. I tested it as far as I could, but sorry, I also have work, other hobbies and university

This issue is not the end of the world. I could understand such hate because of some files deleted or phone bricked, but this is just battery

**Comment by nubesurrealista** [comment]
This is a useless issue.

**Comment by kaduvert** [comment]
> Come on, this is not a big tech company, that's just me, I don't have QAs to test my app
> 
> The problem was in my reading logs loop, you can check the commit with fix to see more
> 
> I don't have enough free time to keep this app enabled for a lot of time in background. I tested it as far as I could, but sorry, I also have work, other hobbies and university
> 
> This issue is not the end of the world. I could understand such hate because of some files deleted or phone bricked, but this is just battery

I think it's important to hold projects like this to a high standard and i hope that you've thought of a way to release your software which can prevent issues like this going all the way to the end user in the future.

It did anger me greatly in that my battery got drained for 2+ weeks, because it ran out in situations where it was extremely critical for my phone to work.

All in all though, i'm very thankful for your amazing work and i wish you the best!
