### ISSUE TITLE
[fr] Auto-capture on crash

### ISSUE THREAD

**Issue by yyy33** [F0x1d/LogFox#165]
Currently, capturing the crash log of an application requires logfox to be running all the time, is it possible to add a module such as xposed to automatically start saving logs and starting logfox when the crashed application crashes. not quite sure if this is technically feasible. This is useful for debugging software that is not quite sure what to do and will crash sometimes.

**Comment by F0x1d** [comment]
For now I can suggest enabling setting in LogFox something like "read logs not from logfox start", it will capture crashes which happened while LogFox was not running

**Comment by yyy33** [comment]
> For now I can suggest enabling setting in LogFox something like "read logs not from logfox start", it will capture crashes which happened while LogFox was not running

Thanks, I didn't realize that was an option
