### ISSUE TITLE
Ability to filter logs for single app

### ISSUE THREAD

**Issue by zt64** [F0x1d/LogFox#22]
Im frequently running into a problem where im trying to view logs for a specific app on my phone but LogFox doesn't really have a neat way of doing it.

What I'm thinking is add an option to the filter that displays all apps including system (toggleable) and the user can select it to show only logs for that app

**Comment by F0x1d** [comment]
I'm too lazy to add apps list, maybe filter for package name is enough?

**Comment by F0x1d** [comment]
Done even with apps list, check it out https://github.com/F0x1d/LogFox/actions/runs/5847132293 in Artifacts section

**Comment by F0x1d** [comment]
Done in 1.3.6
