### ISSUE TITLE
Request: Add LogFox to f-droid

### ISSUE THREAD

**Issue by Davilarek** [F0x1d/LogFox#23]

**Comment by digitalcircuit** [comment]
I'm guessing this issue can now be closed?
https://f-droid.org/packages/com.f0x1d.logfox/

(I saw this app on F-Droid, and took a look at the issues to see where things stand.  This does look nice.)

**Comment by shuvashish76** [comment]
Feel free to use their badge : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md
