### ISSUE TITLE
[Feature request] Add a default primary color

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#32]
Add a default primary color (brand color, orange) for a good viewing experience on devices that do not support dynamic color sampling

![Screenshot_20231002_012302_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/6a561f83-ceea-44fb-9bd2-696821e9bd60)
![Screenshot_20231002_012307_com.huawei.android.launcher.jpg](https://github.com/F0x1d/LogFox/assets/51242302/d3d4226c-76e8-4c6b-a2b1-a7f8d681c5d4)

**Comment by F0x1d** [comment]
Someday. Probably not today. Probably not tomorrow either, but definitely someday.
