### ISSUE TITLE
Group by app 

### ISSUE THREAD

**Issue by PeterKW** [F0x1d/LogFox#39]
Could we have a button to Google crashes grouped by application?

Thank you very much!

E.g 

![Screenshot_20231003-025157.png](https://github.com/F0x1d/LogFox/assets/13779157/a79e27ca-27b3-4e25-b346-298188b8ce2b)

![Screenshot_20231003-025235.png](https://github.com/F0x1d/LogFox/assets/13779157/1b382a98-d344-4a40-8901-6d560652239a)

**Comment by F0x1d** [comment]
I can't think of a suitable design for it in LogFox. Maybe any suggestions?

**Comment by shuvashish76** [comment]
[Scoop](https://github.com/TacoTheDank/Scoop) has this feature
- Combine same apps
- Combine same crashes

I think OP provided the both the screenshots from that app.
