### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by ThIsLinked** [F0x1d/LogFox#4]
Hello. Wanted to suggest some improvements:

1. The current dark theme is more like an AMOLED theme. Is it possible to make the background less black?
<details>
  <summary>Item 1</summary>

![Screenshot_1](https://user-images.githubusercontent.com/45180688/191322095-f6c66879-c64c-4e30-8279-48aabffc404b.jpg)
</details>

2. Maybe add a language selection in the application? It always depends on your system, which is sometimes inconvenient.
<details>
  <summary>Item 2</summary>

![Screenshot_2](https://user-images.githubusercontent.com/45180688/191322934-dc570445-5f58-44e7-9ed7-dd96da8d7fef.jpg)
</details>

3. Do you think it's worth adding the "AndroidRuntime" tag filter on the first launch of the application? This is a very useful filter in case of debugging. And beginners can quickly use it.
<details>
  <summary>Item 3</summary>

![Screenshot_3](https://user-images.githubusercontent.com/45180688/191323033-2e122670-e244-4298-aeeb-fbcc206d96ea.jpg)
</details>

**Comment by F0x1d** [comment]
1) I am going to add dark theme soon
2) This feature is completely useless
3) I think i will add something like default filters
