### ISSUE TITLE
[optimization] Splitting partial fragments into activities

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#40]
Splitting fragments to different activities(especially pages without navigation bars) has the following advantages:

1. Animation Follow System, and avoid the non-animated disappearance of rail or navigation view
2. Remove content protection from navigation bar only for MainActivity, because it is better to set the transparent navigation bar in the portrait home screen. In the original situation, switching to a page without a navigation bar requires manually setting the navigation bar color, as in my pr.
![Screenshot_20231005_185443_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/140809db-3dc0-4079-9922-35e2ebe680ca)

**Comment by F0x1d** [comment]
I don't think it's a good idea. As far as i remember Google has always recommended to use Fragments as much as possible. 

- If you care about dock animations, i can make them

- If you care about navbar color on main screen, that's the thing i don't find really important (as on newer OS versions Android makes scrim automatically). But, again, i can also implement it

**Comment by F0x1d** [comment]
done in 05f05a27bee236c1562af8ae70f8841b6cd61db2
