### ISSUE TITLE
Refactoring Backgrounds, menus for LogsAdapter and LogViewHolder

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#47]
## Backgrounds
Delete these code
![image](https://github.com/F0x1d/LogFox/assets/51242302/c75a96bf-6a19-4e74-aefe-367b37fcc2ec)
![image](https://github.com/F0x1d/LogFox/assets/51242302/e6720f0a-ef44-4043-a3cd-5b757f9169e4)

Because this code is dynamically generated, it may result in reduced readability.

My recommended way to do this is to write the background to the drawable resource folder and then get it in the code.

## Menus

Delete these code.
![image](https://github.com/F0x1d/LogFox/assets/51242302/88d8b1ef-0356-48ba-beab-74952022e121)

I recommend using context menu because it eliminates the need to generate a lot of PopupMenu and makes the menu follow the user's finger!

The minimum Android version of the software is 24, so the context menu can be displayed normally as PopupMenu style

## Ripple

And add a ripple effect to the background. This requires refactoring the background implementation.

**Comment by F0x1d** [comment]
I don't really want to create a separate background drawable for every log level. Log line background can be moved to drawable, yes

**Comment by F0x1d** [comment]
If you can implement this, context menus and then make a PR, it will be really nice. Right now I have exams and no time for LogFox

**Comment by Jesse205** [comment]
After my testing, if the contextmenu uses dynamic colors, it must use a DynamicColors theme. Using the dynamic theme set by the code in the application will not cause the contextmenu to change color
