### ISSUE TITLE
[Feature Request] Make the selection experience like ActionMode

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#53]
The details are as follows:

1. When the user is making a selection, the toolbar displays a back button and the selected quantity, indicating that the user is in selection mode.
2. Click the return button to cancel the selection instead of exiting directly.
3. When not selected, hide or disable the two menus related to selection in the toolbar

This is the current behavior:
![Screenshot_20231014_141107_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/81d468fb-b9a9-4240-b5da-d8d873a055dc)
![Screenshot_20231014_141115_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/974c9c7c-6400-4d79-83fa-c094702cc8ed)

This is the behavior of Material Files:
![Screenshot_20231014_141126_me.zhanghai.android.files.jpg](https://github.com/F0x1d/LogFox/assets/51242302/fd8c3f48-38d0-4d85-918a-ad1803713ac3)

**Comment by F0x1d** [comment]
Done in 48e65c8b5e52e6c1fa030e336ee866ef1d47626a

**Comment by jstetten** [comment]
Hi @F0x1d.

How much work would it take to add a "Select All" button?

If the app we're debugging crashes or experiences its event while we're setting up or in between recording, doing a quick "Select All" + `action` is the only way to capture what just happened.

I'm sure there are plenty of other scenarios where it would be useful as well. Such as: even if a log was successfully recorded, it can still be very enlightening to experiment with searches and filters on the existing logcat before it's lost. Once again, in this case, selecting all results on the screen and performing an action on them is necessary.

Just a suggestion. It's a handy app!

**Comment by F0x1d** [comment]
I guess it's not so hard, i'll add it
