### ISSUE TITLE
[Bug] When browsing the file, the software still keeps refreshing the logs when the list scrolls to the bottom

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#60]
This may lead to performance issues. In addition to this it can also cause talkback to constantly prompt for the scroll position of the list.

## The list doesn't scroll to the bottom
![image](https://github.com/F0x1d/LogFox/assets/51242302/9ece43c2-24ed-4e66-8004-6f85282b9ad4)

## The list has scrolled to the bottom
![image](https://github.com/F0x1d/LogFox/assets/51242302/0177b901-177b-4d60-a55d-31d80255cc7d)

**Comment by F0x1d** [comment]
Should be resolved in 815bfc586ae4647a0d6f1d88ab9c01c60097b81f
