### ISSUE TITLE
How about changing the icon of the log and crashs.

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#63]
I suggest changing the log icon in the navigation bar and notification bar to logfox icons, and changing the crash icon to bug. I think the meaning of bug is closer to crashes.

Moreover, the logcat icon on Android Studio is the same as the cat icon, so it is more reasonable to set the log icon to the logfox icon.

**Comment by F0x1d** [comment]
Only if @the-dise can animate app's logo for logs screen for bottom navigation

**Comment by F0x1d** [comment]
Looks like there won't be any response from him. Maybe there is someone who can make a sort of animation for app logo for bottom navigation?
