### ISSUE TITLE
Hi Feature request

### ISSUE THREAD

**Issue by Levantosa** [F0x1d/LogFox#66]
Im a software tester ,i need a option to hide build fingerprints in log for privacy,it helps me to feedback devs faster. i mentioned build fingerprints as phone software informations.

**Comment by F0x1d** [comment]
You mean `device.txt` file? Or some specific logs with data you want to hide? If it is the latter option, then, please, provide an example

**Comment by Levantosa** [comment]
yeah the device.txt file (aka) contents in build props.

**Comment by F0x1d** [comment]
Can you provide an example of such logs?

**Comment by F0x1d** [comment]
BTW, you can use filters to exclude such logs

**Comment by Levantosa** [comment]
how to do this using filters,do u have documentation.

**Comment by F0x1d** [comment]
On main screen tap three dots in top right corner, then "filters". There you can create a new one by using "plus" button in bottom right corner. Select "excluding" and fill the fields. I guess you will need the field "Content contains". You can create as many filters as you want. They will be joined by "or" operator by LogFox to filter logs

**Comment by F0x1d** [comment]
I guess it can cover your needs

**Comment by Levantosa** [comment]
Dear Dev, I can't able to reproduce exclude content contains of what I need to remove from log capture,may u explain elaborately.

**Comment by F0x1d** [comment]
Contact me in Telegram: @F0x1d. I hope i will be more helpful there

**Comment by Levantosa** [comment]
More users popping in your user name ,u may share ur I'd  number.

**Comment by F0x1d** [comment]
Telegram usernames are unique, you can try [this link](tg://user?id=5794159871)
