### ISSUE TITLE
Log that precedes the app launch

### ISSUE THREAD

**Issue by opk12** [F0x1d/LogFox#76]
Is it possible to have the log that precedes the moment the app is launched, as in Logcat Reader ([GitHub](https://github.com/darshanparajuli/LogcatReader), [F-droid](https://f-droid.org/en/packages/com.dp.logcatapp/))?

Note that Logcat Reader's recording service with the mandatory notification is started when the app is launched, and it is not running before; I did "Force stop" in the Android settings, to be sure.

**Comment by F0x1d** [comment]
It is possible, but this way it will cause conflicts with crashes observer. 

Crashes observer reads every log line, so this way it can read some crashes twice (first time when crash occurred and after the app is reopened after force stop, for example)

Of course i can make LogFox support it, but is it really needed?

**Comment by opk12** [comment]
Ah, I get it. Thank you for looking into it. I am not an Android dev and my stack traces are from new features of F-droid apps. I open the log after the crash (happens circa once a month) and copy-paste straight into GH. I do not take the time to find minimal reproducer steps anyway, as the stack trace is usually clear enough. So if I switched to LogFox, I would not be using the crash observer. But I understand that for example, it may be different for a nightly beta tester.

I don't know if that's feasible, but [this SO post](https://stackoverflow.com/a/75870051) suggests some calls to find the app start time.

**Comment by F0x1d** [comment]
Done in v1.5.2
