### ISSUE TITLE
Adapt to Huawei old system

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#80]
![Screenshot_20231211-201428.jpg](https://github.com/F0x1d/LogFox/assets/51242302/5a18a6ff-5fe5-4041-ae09-c56a3c4ef1a7)

![Screenshot_20231211-201433.jpg](https://github.com/F0x1d/LogFox/assets/51242302/d4531cb0-bd9f-4d6e-b3fb-d8e96c715db1)

![Screenshot_20231211-202704.jpg](https://github.com/F0x1d/LogFox/assets/51242302/41aa7a0b-ed3c-47f4-b99d-2fffc50706dc)

1. Huawei's notification icons allow for colorful icons, so they will not be automatically colored like AOSP
    - Solution: Copy a dedicated icon file for notifications and manually fill the file with colors
2. Huawei's navigation bar is gray by default, not white, and it is the same behavior in new EMUI now.
    - Solution: Remove the navigation bar background on Huawei devices, regardless of whether the device is Android 8.1+  or use a darker background instead (not recommended as it may not look good)

This is your app, you can decide to fix this 💩 bug on huawei or ignore it. I would greatly appreciate it if you could fix this bug. I can also provide you with some help.

**Comment by F0x1d** [comment]
- 1 will not be fixed
- 2 maybe

**Comment by F0x1d** [comment]
done in v1.5.3

**Comment by Jesse205** [comment]
Hello, for the new version of Huawei devices, when setting navigation bar behavior, you can consider it as a regular AOSP device.

Just set a darker color or leave it blank for Huawei devices when setting the mask.

**Comment by F0x1d** [comment]
Didn't understand you? I've already done it?

**Comment by Jesse205** [comment]
I'm very sorry I didn't express myself clearly.II made aI made a picture.
![image](https://github.com/F0x1d/LogFox/assets/51242302/13d33fb0-ac50-4ee1-b7a8-bdd8eac7499d)

**Comment by F0x1d** [comment]
Am i right here 4481990edfb5751693f0005df5e1fd478119f751?

**Comment by Jesse205** [comment]
All right
