### ISSUE TITLE
[Bug] The input in the dialog may not be visible on small screen phones.

### ISSUE THREAD

**Issue by Jesse205** [F0x1d/LogFox#87]
![Screenshot_20231220_111344_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/4a261bd6-6050-406e-be0e-47d6195ee7aa)

**Comment by F0x1d** [comment]
Check if it is fixed in https://github.com/F0x1d/LogFox/actions/runs/7311190174

**Comment by Jesse205** [comment]
I downloaded this version, but this bug still exists.

**Comment by F0x1d** [comment]
But the text field can be scrolled now. I guess there is no other fix but to change your DPI

**Comment by Jesse205** [comment]
> But the text field can be scrolled now. I guess there is no other fix but to change your DPI

![Screenshot_20231224_203656_com.activitymanager.jpg](https://github.com/F0x1d/LogFox/assets/51242302/b33f228e-bfe0-4099-95df-41f82a25e4f1)
Another app, ActivityManager, can make the height of the dialog box not change with the input method. I think you can refer to it.

https://github.com/sdex/ActivityManager

**Comment by F0x1d** [comment]
Should be fixed [here](https://github.com/F0x1d/LogFox/actions/runs/7314903088)

**Comment by Jesse205** [comment]
Yes, this issue has been resolved.
