### ISSUE TITLE
[FR] Black theme or fully dynamic BG color like in earlier versions (≤1.5.2)

### ISSUE THREAD

**Issue by Username1-a** [F0x1d/LogFox#88]
Hello, please, add an option to enable Black theme in LogFox. 

Alternatively, if possible, you can make Monet theming like it was in the previous version (version 1.5.2 and earlier), i.e. fully dynamic – due to questionable changes in material3 compose, background color is no longer dynamic (you can't make it darker/lighter/completely black with the use of apps like "Repainter" anymore), some app developers ignore this change, still allowing user to fully customize the Monet theme in their app.

Here's screenshots comparing LogFox v1.5.2 and v1.5.3 with "Repainter" enabled:
![Screenshot_20231222-152031_LogFox~3](https://github.com/F0x1d/LogFox/assets/47947180/97f0fba5-f05b-487c-ba05-fa35f70b9248)

[
![Screenshot_20231222-152406_LogFox~2](https://github.com/F0x1d/LogFox/assets/47947180/ab463b94-c326-4347-8347-2179a9fbb0be)
](url)

Anyway, good luck to you and thank you for your app

**Comment by Jesse205** [comment]
Hello, what app did you use to achieve dynamic colors?

**Comment by Jesse205** [comment]
> > Hello, what app did you use to achieve dynamic colors?
> 
> Hello. It's "Repainter" (https://play.google.com/store/apps/details?id=dev.kdrag0n.dyntheme). 
> There also several other apps that allows Monet theming customization, like "Colorblendr" (https://github.com/Mahmud0808/ColorBlendr). 
> Also, such customizations often included into many Android >12 custom ROMs

thank you.

**Comment by Jesse205** [comment]
![Screenshot_2023-12-25-23-29-50-865_com.miui.home.jpg](https://github.com/F0x1d/LogFox/assets/51242302/5524eb41-65f9-4afc-ba6f-92bf7806a25e)
![Screenshot_2023-12-25-23-29-57-937_com.dede.android_eggs.jpg](https://github.com/F0x1d/LogFox/assets/51242302/258f8c44-14b4-4f27-b4c3-c2c96b5c8980)
![Screenshot_2023-12-25-23-34-26-150_com.f0x1d.logfox.jpg](https://github.com/F0x1d/LogFox/assets/51242302/9801dfd1-977a-4c98-9eca-9b1a736074b4)
Many of the dark natural colors in the latest material components v1.11 are based on N2 600 color. However, the black background of the xposed module is achieved by modifying 1000 colors, which can cause this bug.

**Comment by Jesse205** [comment]
I've created a [pr](https://github.com/F0x1d/LogFox/pull/91) which adds a black themed switch within the app.

Also, I think the xposed modules need to implement the ability to tamper with `android:lStar` in color resources to make sure MaterialComponent v1.11+ works.

Solving the failure issue through LogFox itself is also very simple, just continue to use colorSurface+colorPrimary+elevation to calculate the color. However, it requires rewriting a bunch of widget themes above v1.11, and this approach has been discontinued.

**Comment by Jesse205** [comment]
Unfortunately, the maintainer does not want to implement this feature. You can download https://github.com/Jesse205/LogFox/actions/runs/7348124779, this version implements the black mode
You can view the source code here: https://github.com/Jesse205/LogFox/tree/feat_black_theme

**Comment by Jesse205** [comment]
> @Jesse205 Thank you very much for your efforts
> 
> > Also, I think the xposed modules need to implement the ability to tamper with `android:lStar` in color resources to make sure MaterialComponent v1.11+ works.
> 
> It would be great if you could share your insights with Mahmud0808, the dev behind Colorblendr, if it's not too distracting for you, of course

You can reach him here: https://github.com/Mahmud0808/ColorBlendr/issues. I have created an issue

**Comment by F0x1d** [comment]
I guess it can be closed? The new `ColorBlendr` version is released
