### ISSUE TITLE
How to save since the boot

### ISSUE THREAD

**Issue by megapinky** [F0x1d/LogFox#99]
Hi, I'm using Las version 1.5.4 an the only option to save the log is by record, but I need to save full log, since boot, it is possible? How to save the info on the main window?
![Screenshot_20240130-213753_LogFox](https://github.com/F0x1d/LogFox/assets/43482955/072fb042-c01c-45e9-a527-0b36f432342a)

**Comment by F0x1d** [comment]
done in 49480cdfa0dba107772215b0f943daa56617601a
